services:
  app:
    image: php:8.2-apache
    container_name: laravel_app
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
    ports:
      - "8080:80"
    environment:
      - APACHE_DOCUMENT_ROOT=/var/www/html/public
    depends_on:
      - db
      - redis
    command: >
      bash -c "apt-get update &&
               apt-get install -y libpq-dev unzip &&
               docker-php-ext-install pdo pdo_mysql pdo_pgsql &&
               a2enmod rewrite &&
               curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer &&
               apache2-foreground"
  db:
    image: postgres:15
    container_name: postgres_db
    environment:
      POSTGRES_DB: camara_dados
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"
volumes:
  pgdata:
